server:
  port: 8088

spring:
   datasource:
     username: root
     url: jdbc:mysql://localhost:3306/fixeddeposit
     password: examly
   jpa:
     database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
     hibernate:
       ddl-auto: update
       show-sql: true
   application:
     name: FIXED-DEPOSIT-SERVICE
